### PR TITLE
Impelement JSON interface in View Service functions

### LINKED ISSUE #192: Integrate json interface into view service functions
The Web application is used to access an OPC UA Web server via a json Web socket interface. For this purpose, the following functions must be provided in json format.

- Browse request/response
- BrowseNext request/response
- TranslateProwsePathsToNodeIds

### PR DESCRIPTION
**Pull request by flipback**
Closes #192

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

A new feature

* **What is the current behavior?** (You can also link to an open issue here)

Currently supported only OPC UA Binary format

* **What is the new behavior (if this is a feature change)?**

The PR  provides JSON decoding\encoding requests and responses of VIew Services

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

Not

### CODE REVIEW

**Comment by flipback** [comment]
Hi @huebl , I've implemented only one class to show my idea. If it is ok for you, I'll go on developing the rest of the classes.

**Comment by huebl** [comment]
Hi @flipback, I like your concept. 

Remarks:

I would extend the class JSON Formatter a little bit. The decoder function assumes that the element must always be included in the JSON document. If the element does not exist, the decoding is aborted with an error. Elements can be optionally included in a JSON document. We have to take that into account.

For all elements of the standard data types, the OPC UA information model defines whether they are mandatory or optional. This is not so clear in the opc ua specification for the request and response classes. Here we must determine for each element itself whether the element is obligatory or optional.

The output of typeid (x) .name () depends on the compiler used. There are big differences between the different compilers and therefore also between the different operating systems. I have already seen that only a cryptic string was issued. I would leave it that way for now. But we should check that the output provides readable results on all systems.

**Comment by flipback** [comment]
Concerning optional elements:

For decoding I can add boolean flag 'optional' to `jsonDecode`. But what shall I do for encoding? To use a mask or to encode all elements?

About `typeid`.. I can get rid of it by adding class name to JsonFormatter's constructor.

**Comment by huebl** [comment]
I do not really have a good solution for the encoding. At various points I check the value of the variable, the array length, nullptr, .., etc. That's not really nice. For the decoding an option is ok. 

I would let the typeid instruction inside. Maybe there is no problem with the new compiler. If there are problems you can still change that later. The number of data structures can be very large. A variable with the name of the class in each instance can consume a lot of memory.

**Comment by flipback** [comment]
I see. By my experience, there are several ways to solve the problem to encode\decode data:

1. Manual. What we're doing now. 
2. Code generation. We give a code generator some meta-information (type, name, default value, optional flag, etc.) about data structures in XML, JSON or YML formats and it generates some basic classes with fields, accessors and encde\decode methods. Then we develop domain-specific code in inherited classes. This approach is working fast in runtime but makes the compilation time longer.
3. Storing meta-information in runtime. Every class registers its fields in some dictionary with meta-information and provides access to it for classes, that implements decode\encode to specific formats Binary, XML, JSON, etc. It is a very scalable way and can be mixed with code generation not to register fields manually. However, it consumes a lot of memory to store the dictionary. 
4. Reflection. All meta-information is described in annotations (or attributes, or decorators depending on the language). Unfortunately, it isn't for C++.

I don't say we need to implement one of them right now. I'm just sharing my view on the problem that is very common for many projects.

**Comment by flipback** [comment]
As a result of our conversation, I've added the following features:
1) an optional flag and a default value for numeric fields. If an object is decoded, the default value is used to init field when the decoding failed and the field is optional. If an object is encoded, the filed is skipped if it equals default value and it is optional. 
2) field represented by pointers can be null if they are optional and must implement JsonFormatter interface.

If this workaround is acceptable, I'll write some unit tests for JsonFormmater and go on with the issue.

**Comment by huebl** [comment]
We should also do that later in the code generators.

**Comment by flipback** [comment]
Hi @huebl, the PR is ready for review.

**Pull request merged**
