### PR TITLE
Implement Windows CI with AppVeyor

### LINKED ISSUE #77: Windows CI with AppVeyor
In order to prevent compilation errors on Windows, we need to build the stack on Windows automatically.

### PR DESCRIPTION
**Pull request by flipback**
Closes #77

### CODE REVIEW

**Comment by flipback** [comment]
Hi. @huebl . Unfortunately, I didn't manage to set up the compilation and the tests with Appeyor. The compilation is too slow and is interrupted by the timeout. I tried to use the cache and make the compilation incremental, but it is not working on Appeyor.  My best result is the building only the stack with Ninja. So we can only check if the stack is compiled on Windows at all.

**Comment by huebl** [comment]
@flipback 

 At least we can check if the software is translated under Windows. For the version 3 that is enough for me in the first place.

In version 4, the problem with the timeout is much larger. There are several 100 new files in this version. The duration of the build is already over 50 minutes. Travis CI breaks off the build. I do not have a solution yet.

**Comment by huebl** [comment]
@flipback 

In the first step, a separation of stack and test should be performed. That should help us a lot. I would not separate the OpcUaStackCore, OpcUaStackClient, and the OpcUaStackServer.  The other parts (Client, Server, Builder, Generator, ...) could also be separated. The seperation is not possible in version 3. There are too many conflicts with version 4. For this reason, I put the problem back once.

Unfortunately there is no test pipeline in Travis. That would fix the problem.

**Comment by flipback** [comment]
Ok, I see. Then you can merge the PR. We return to the problem in version 4.

**Pull request merged**
